version: '2'

services:
    postgres:
        build:  postgresql/
        container_name: postgres
        ports:
        - "5439:5432"
        volumes:
        - ./data/db:/var/lib/postgresql/data

    miniverse:
        build:  miniverse/
        container_name: miniverse
        ports:
        - "8086:5000"
        depends_on:
          - postgres
