version: '2'

services:
    postgres:
        build:  postgresql/
        container_name: db
        ports:
        - "5435:5432"
        volumes:
        - ./data/db:/var/lib/postgresql/data

    miniverse:
        build:  miniverse/
        container_name: miniverse
        ports:
        - "8086:8000"
        volumes:
        - ./data/miniverse:/var/lib
